# Generated by Django 3.2.12 on 2023-02-09 16:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameUsers',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('id', models.BigIntegerField(unique=True)),
                ('is_bot', models.BooleanField()),
                ('language_code', models.CharField(max_length=4)),
                ('score', models.BigIntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
                ('message_id', models.CharField(max_length=200)),
                ('is_message', models.BooleanField(default=False)),
                ('average_time', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('session_fist_active', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_last_active', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_time', models.FloatField(default=0)),
                ('game_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gameusers')),
            ],
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('surname', models.CharField(blank=True, max_length=255, verbose_name='Surname')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Joined at')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is admin/manager')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'SiteUser',
                'verbose_name_plural': 'SiteUsers',
            },
        ),
        migrations.CreateModel(
            name='ActiveSessionLedger',
            fields=[
                ('game_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.gameusers')),
                ('game_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.gamesession')),
            ],
        ),
    ]
