# Generated by Django 3.2.12 on 2023-01-08 16:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameUsers',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('id', models.BigIntegerField(unique=True)),
                ('is_bot', models.BooleanField()),
                ('language_code', models.CharField(max_length=4)),
                ('score', models.BigIntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
                ('message_id', models.CharField(max_length=200)),
                ('is_message', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('session_fist_active', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_last_active', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_time', models.FloatField(default=0)),
                ('game_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gameusers')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveSessionLedger',
            fields=[
                ('game_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.gameusers')),
                ('game_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.gamesession')),
            ],
        ),
    ]
