# Generated by Django 3.2.12 on 2023-02-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameusers',
            name='average_time',
            field=models.FloatField(default=0),
        ),
    ]
