# Generated by Django 3.2.12 on 2023-02-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameusers',
            name='chat_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
