# Generated by Django 3.2.12 on 2023-02-27 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_gameusers_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('use_count', models.IntegerField(default=0)),
                ('first_use_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
