# Generated by Django 3.2.12 on 2023-02-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_siteuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteUser',
        ),
    ]
